# 베이스 이미지 설정
FROM python:3.9

# 작업 디렉토리 설정
WORKDIR /app

# 라이브러리 설치
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# 어플리케이션 코드 복사
COPY . .

# 어플리케이션 실행
CMD ["python", "main.py"]
